/**********************************/
/* Table Name: 예약 */
/**********************************/
CREATE TABLE RESERVE(
    RESERVENO                         NUMBER(20)     NOT NULL    PRIMARY KEY,
    MEMBERNO                          NUMBER(10)     NOT NULL,
    RESTCONTENTSNO                    NUMBER(20)     NOT NULL,
    COMMENTNO                         NUMBER(10)     NULL ,
  FOREIGN KEY (MEMBERNO) REFERENCES MEMBER (MEMBERNO),
  FOREIGN KEY (RESTCONTENTSNO) REFERENCES RESTCONTENTS (RESTCONTENTSNO)
);

COMMENT ON TABLE RESERVE is '예약';
COMMENT ON COLUMN RESERVE.RESERVENO is '예약번호';
COMMENT ON COLUMN RESERVE.MEMBERNO is '회원 번호';
COMMENT ON COLUMN RESERVE.RESTCONTENTSNO is '맛집 컨텐츠 번호';
COMMENT ON COLUMN RESERVE.COMMENTNO is '댓글 번호';